<?php

use Doctrine\ORM\EntityRepository;

/**
 * BugRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class BugRepository extends EntityRepository
{
}
